---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: nginx-ingress-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "false"
spec:
  chartGitPath: nginx-ingress
  releaseName: nginx-ingress-dev
  values: